@id = b57b192257e7e93c636c59c8ccd2d366
GET https://api.themoviedb.org/3/movie/{movie_id}?api_key=<<api_key>>&language=en-US

###

GET https://api.themoviedb.org/3/discover/movie?api_key=b57b192257e7e93c636c59c8ccd2d366&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1


###

GET https://api.themoviedb.org/3/search/movie?api_key={{id}}&language=en-US&page=1&include_adult=false&query=iron man